#!/usr/bin/env python3
"""Generate public synthetic CLI fixtures without using keyhunt arithmetic.

This small affine implementation is a fixture generator, not production crypto
or the independently pinned differential oracle required by milestone C06.
"""
import hashlib
import json
import subprocess
from pathlib import Path

P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F
G = (0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798,
     0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8)
ALPHABET = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def add(a, b):
    if a is None:
        return b
    if b is None:
        return a
    x, y = a
    u, v = b
    if x == u and (y + v) % P == 0:
        return None
    slope = ((3 * x * x) * pow(2 * y, -1, P) if a == b
             else (v - y) * pow(u - x, -1, P)) % P
    nx = (slope * slope - x - u) % P
    return nx, (slope * (x - nx) - y) % P


def multiply(k):
    point, step = None, G
    while k:
        if k & 1:
            point = add(point, step)
        step = add(step, step)
        k >>= 1
    return point


def base58(data):
    n, result = int.from_bytes(data, "big"), ""
    while n:
        n, digit = divmod(n, 58)
        result = ALPHABET[digit] + result
    return "1" * (len(data) - len(data.lstrip(b"\0"))) + result


def hash160(data):
    digest = hashlib.sha256(data).digest()
    try:
        return hashlib.new("ripemd160", digest).digest()
    except ValueError:
        # Some Python/OpenSSL builds omit RIPEMD-160; the optional generator
        # can use the system OpenSSL CLI. Running the fixtures needs neither.
        return subprocess.run(["openssl", "dgst", "-provider", "legacy", "-ripemd160", "-binary"],
                              input=digest, stdout=subprocess.PIPE,
                              check=True, timeout=5).stdout


def vector(k):
    x, y = multiply(k)
    assert (y * y - x * x * x - 7) % P == 0
    result = {"scalar": f"{k:x}", "x": f"{x:064x}"}
    for label, pub in [("compressed", bytes([2 + (y & 1)]) + x.to_bytes(32, "big")),
                       ("uncompressed", b"\x04" + x.to_bytes(32, "big") + y.to_bytes(32, "big"))]:
        digest = hash160(pub)
        assert len(digest) == 20
        payload = b"\0" + digest
        check = hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
        result[label] = {"public_key": pub.hex(), "hash160": digest.hex(),
                         "address": base58(payload + check)}
    return result


def generate():
    values = [1, 2, 3, 0xfff, 0x1000, 0x1001, 0x1002, 0x13ff, 0x1400,
              0x1401, 0x17fe, 0x17ff, 0x1800, 0x1801, 0x1bfe, 0x1bff,
              0x100000, 0x100001, 0x100002, 0x200000, 0x200001, 0x200002,
              0x300000, 0x300001, 0x400000, (1 << 80) + 0x1000,
              (1 << 80) + 0x13ff, (1 << 80) + 0x1400]
    vectors = {f"{k:x}": vector(k) for k in values}
    assert vectors['1']['compressed']['address'] == '1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH'
    assert vectors['1']['uncompressed']['address'] == '1EHNa6Q4Jz2uvNExL497mE43ikXhwF6kZm'
    # First checksum-valid minikey after the all-ones base; matches the CLI's
    # increment-before-check convention. Everything here is public test data.
    n = 1
    while True:
        remaining, suffix = n, ""
        while remaining:
            remaining, digit = divmod(remaining, 58)
            suffix = ALPHABET[digit] + suffix
        mini = "S" + suffix.rjust(21, "1")
        if hashlib.sha256((mini + "?").encode()).digest()[0] == 0:
            break
        n += 1
    key = int.from_bytes(hashlib.sha256(mini.encode()).digest(), "big")
    return {"description": "Synthetic public fixtures; generated by generate_vectors.py",
            "vectors": vectors,
            "ethereum_scalar_1": "0x7e5f4552091a69125d5dfcb7b8c2659029395bdf",
            "minikey": {"base": "S" + "1" * 21, "value": mini, **vector(key)}}


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = Path(__file__).with_name('vectors.json')
    content = json.dumps(generate(), indent=2) + '\n'
    if args.check:
        if path.read_text() != content:
            raise SystemExit('vectors.json differs from regenerated fixtures')
        print('Fixture regeneration matches vectors.json')
    else:
        path.write_text(content)
