add_executable(bsgs_table_test tests/unit/bsgs_table.cpp)
target_link_libraries(bsgs_table_test PRIVATE keyhunt_core)
keyhunt_configure_target(bsgs_table_test)
add_test(NAME bsgs_table_contract COMMAND bsgs_table_test)
set_tests_properties(bsgs_table_contract PROPERTIES TIMEOUT 120 LABELS "cpu;bsgs;tables")
add_test(NAME bsgs_table_oracle COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_table.py"
    --binary $<TARGET_FILE:keyhunt> --oracle $<TARGET_FILE:secp256k1_oracle>
    --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-table-results.json")
set_tests_properties(bsgs_table_oracle PROPERTIES TIMEOUT 180 LABELS "cpu;bsgs;tables;oracle")
if(KEYHUNT_ENABLE_HIP)
    add_executable(hip_bsgs_table_test tests/gpu/bsgs_table.hip)
    target_include_directories(hip_bsgs_table_test PRIVATE kernels/hip src/backend/hip)
    target_link_libraries(hip_bsgs_table_test PRIVATE keyhunt_backend)
    set_target_properties(hip_bsgs_table_test PROPERTIES LINKER_LANGUAGE CXX INTERPROCEDURAL_OPTIMIZATION OFF)
    add_test(NAME hip_bsgs_table COMMAND hip_bsgs_table_test)
    set_tests_properties(hip_bsgs_table PROPERTIES TIMEOUT 120 LABELS "hip;hardware;bsgs;tables" RESOURCE_LOCK hip_device)
endif()
set(bsgs_device_args)
if(KEYHUNT_ENABLE_HIP)
    list(APPEND bsgs_device_args --hip)
endif()
add_test(NAME bsgs_table_devices COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_devices.py"
    --binary $<TARGET_FILE:keyhunt> --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-devices-results.json" ${bsgs_device_args})
set_tests_properties(bsgs_table_devices PROPERTIES TIMEOUT 180 LABELS "cpu;backend;bsgs")
if(KEYHUNT_ENABLE_HIP)
    set_tests_properties(bsgs_table_devices PROPERTIES LABELS "hip;hardware;bsgs;tables" RESOURCE_LOCK hip_device)
endif()

if(KEYHUNT_ENABLE_HIP)
    add_executable(hip_bsgs_failure_test tests/gpu/bsgs_failures.hip src/backend/hip/bsgs_table.hip)
    target_include_directories(hip_bsgs_failure_test PRIVATE kernels/hip src/backend/hip)
    target_compile_definitions(hip_bsgs_failure_test PRIVATE KEYHUNT_TEST_HIP_FAILURES=1)
    target_link_libraries(hip_bsgs_failure_test PRIVATE keyhunt_core)
    set_target_properties(hip_bsgs_failure_test PROPERTIES LINKER_LANGUAGE CXX INTERPROCEDURAL_OPTIMIZATION OFF)
    add_test(NAME hip_bsgs_failures COMMAND hip_bsgs_failure_test)
    set_tests_properties(hip_bsgs_failures PROPERTIES TIMEOUT 120 LABELS "hip;hardware;bsgs;tables" RESOURCE_LOCK hip_device)
endif()
if(KEYHUNT_ENABLE_HIP)
    add_executable(hip_bsgs_benchmark tests/gpu/bsgs_benchmark.cpp)
    target_link_libraries(hip_bsgs_benchmark PRIVATE keyhunt_backend)
    set_target_properties(hip_bsgs_benchmark PROPERTIES LINKER_LANGUAGE CXX)
endif()
