add_executable(bsgs_search_test tests/unit/bsgs_search.cpp)
target_link_libraries(bsgs_search_test PRIVATE keyhunt_core)
keyhunt_configure_target(bsgs_search_test)
add_test(NAME bsgs_search_contract COMMAND bsgs_search_test)
set_tests_properties(bsgs_search_contract PROPERTIES TIMEOUT 60 LABELS "cpu;bsgs;core")

if(KEYHUNT_ENABLE_HIP)
    add_executable(hip_bsgs_search_test tests/gpu/bsgs_search.cpp)
    target_link_libraries(hip_bsgs_search_test PRIVATE keyhunt_backend)
    set_target_properties(hip_bsgs_search_test PROPERTIES LINKER_LANGUAGE CXX)
    add_test(NAME hip_bsgs_search COMMAND hip_bsgs_search_test)
    add_executable(hip_bsgs_search_failure_test tests/gpu/bsgs_search_failures.hip src/backend/hip/bsgs_search.hip src/backend/hip/bsgs_table.hip)
    target_include_directories(hip_bsgs_search_failure_test PRIVATE kernels kernels/hip src/backend/hip)
    target_compile_definitions(hip_bsgs_search_failure_test PRIVATE KEYHUNT_TEST_HIP_FAILURES=1)
    target_link_libraries(hip_bsgs_search_failure_test PRIVATE keyhunt_core)
    set_target_properties(hip_bsgs_search_failure_test PROPERTIES LINKER_LANGUAGE CXX INTERPROCEDURAL_OPTIMIZATION OFF)
    add_test(NAME hip_bsgs_search_failures COMMAND hip_bsgs_search_failure_test)
    set_tests_properties(hip_bsgs_search hip_bsgs_search_failures PROPERTIES TIMEOUT 120 LABELS "hip;hardware;bsgs" RESOURCE_LOCK hip_device)
endif()
set(bsgs_search_args)
if(KEYHUNT_ENABLE_HIP)
    list(APPEND bsgs_search_args --hip)
endif()
add_test(NAME bsgs_cli COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_cli.py" --binary $<TARGET_FILE:keyhunt>
    --oracle $<TARGET_FILE:secp256k1_oracle> --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-cli-results.json" ${bsgs_search_args})
set_tests_properties(bsgs_cli PROPERTIES TIMEOUT 300 LABELS "cpu;backend;bsgs")
if(KEYHUNT_ENABLE_HIP)
    set_tests_properties(bsgs_cli PROPERTIES LABELS "hip;hardware;bsgs;oracle" RESOURCE_LOCK hip_device)
    add_test(NAME bsgs_cli_single COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_cli.py" --binary $<TARGET_FILE:keyhunt>
        --oracle $<TARGET_FILE:secp256k1_oracle> --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-cli-single-results.json" --hip --group 1)
    set_tests_properties(bsgs_cli_single PROPERTIES TIMEOUT 300 LABELS "hip;hardware;bsgs;oracle" RESOURCE_LOCK hip_device)
endif()
if(KEYHUNT_ENABLE_HIP)
    add_executable(hip_bsgs_search_benchmark tests/gpu/bsgs_search_benchmark.cpp)
    target_link_libraries(hip_bsgs_search_benchmark PRIVATE keyhunt_backend)
    set_target_properties(hip_bsgs_search_benchmark PROPERTIES LINKER_LANGUAGE CXX)
endif()

if(KEYHUNT_ENABLE_HIP)
    add_test(NAME bsgs_cli_grouped COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_cli.py" --binary $<TARGET_FILE:keyhunt>
        --oracle $<TARGET_FILE:secp256k1_oracle> --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-cli-grouped-results.json" --hip --group 8)
    set_tests_properties(bsgs_cli_grouped PROPERTIES TIMEOUT 300 LABELS "hip;hardware;bsgs;oracle" RESOURCE_LOCK hip_device)
endif()
