add_executable(bsgs_table_test tests/unit/bsgs_table.cpp)
target_link_libraries(bsgs_table_test PRIVATE keyhunt_core)
keyhunt_configure_target(bsgs_table_test)
add_test(NAME bsgs_table_contract COMMAND bsgs_table_test)
set_tests_properties(bsgs_table_contract PROPERTIES TIMEOUT 120 LABELS "cpu;bsgs;tables")
add_test(NAME bsgs_table_oracle COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_table.py"
    --binary $<TARGET_FILE:keyhunt> --oracle $<TARGET_FILE:secp256k1_oracle>
    --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-table-results.json")
set_tests_properties(bsgs_table_oracle PROPERTIES TIMEOUT 180 LABELS "cpu;bsgs;tables;oracle")
if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_bsgs_table_test tests/gpu/bsgs_table.hip)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_bsgs_table_test PRIVATE keyhunt_gpu_options)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_bsgs_table_test PRIVATE kernels/search src/backend/gpu)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_bsgs_table_test PRIVATE keyhunt_backend)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_bsgs_table_test PROPERTIES LINKER_LANGUAGE CXX INTERPROCEDURAL_OPTIMIZATION OFF)
    add_test(NAME ${KEYHUNT_GPU_BACKEND}_bsgs_table COMMAND ${KEYHUNT_GPU_BACKEND}_bsgs_table_test)
    set_tests_properties(${KEYHUNT_GPU_BACKEND}_bsgs_table PROPERTIES TIMEOUT 120 LABELS "${KEYHUNT_GPU_BACKEND};hardware;bsgs;tables" RESOURCE_LOCK gpu_device)
endif()
set(bsgs_device_args)
if(KEYHUNT_ENABLE_GPU)
    list(APPEND bsgs_device_args --hardware --backend ${KEYHUNT_GPU_BACKEND})
endif()
add_test(NAME bsgs_table_devices COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/bsgs_devices.py"
    --binary $<TARGET_FILE:keyhunt> --report "${CMAKE_CURRENT_BINARY_DIR}/bsgs-devices-results.json" ${bsgs_device_args})
set_tests_properties(bsgs_table_devices PROPERTIES TIMEOUT 180 LABELS "cpu;backend;bsgs")
if(KEYHUNT_ENABLE_GPU)
    set_tests_properties(bsgs_table_devices PROPERTIES LABELS "${KEYHUNT_GPU_BACKEND};hardware;bsgs;tables" RESOURCE_LOCK gpu_device)
endif()

if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_bsgs_failure_test tests/gpu/bsgs_failures.hip src/backend/gpu/bsgs_table.cpp)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_bsgs_failure_test PRIVATE keyhunt_gpu_options)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_bsgs_failure_test PRIVATE kernels/search src/backend/gpu)
    target_compile_definitions(${KEYHUNT_GPU_BACKEND}_bsgs_failure_test PRIVATE KEYHUNT_TEST_GPU_FAILURES=1)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_bsgs_failure_test PRIVATE keyhunt_core)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_bsgs_failure_test PROPERTIES LINKER_LANGUAGE CXX INTERPROCEDURAL_OPTIMIZATION OFF)
    add_test(NAME ${KEYHUNT_GPU_BACKEND}_bsgs_failures COMMAND ${KEYHUNT_GPU_BACKEND}_bsgs_failure_test)
    set_tests_properties(${KEYHUNT_GPU_BACKEND}_bsgs_failures PROPERTIES TIMEOUT 120 LABELS "${KEYHUNT_GPU_BACKEND};hardware;bsgs;tables" RESOURCE_LOCK gpu_device)
endif()
if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_bsgs_benchmark tests/gpu/bsgs_benchmark.cpp)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_bsgs_benchmark PRIVATE keyhunt_gpu_options)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_bsgs_benchmark PRIVATE keyhunt_backend)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_bsgs_benchmark PROPERTIES LINKER_LANGUAGE CXX)
endif()
