add_executable(ethereum_search_test tests/unit/ethereum_search.cpp)
target_link_libraries(ethereum_search_test PRIVATE keyhunt_core)
keyhunt_configure_target(ethereum_search_test)
add_test(NAME ethereum_search_contract COMMAND ethereum_search_test)
set_tests_properties(ethereum_search_contract PROPERTIES TIMEOUT 30 LABELS "cpu;core;ethereum")

add_executable(portable_keccak_probe tests/gpu/keccak_probe.cpp)
target_include_directories(portable_keccak_probe PRIVATE kernels)
keyhunt_configure_target(portable_keccak_probe)
set(keccak_backends portable)
if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_keccak_probe tests/gpu/keccak_probe.hip)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_keccak_probe PRIVATE keyhunt_gpu_options)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_keccak_probe PRIVATE kernels src/backend/gpu)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_keccak_probe PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF LINKER_LANGUAGE CXX)
    list(APPEND keccak_backends ${KEYHUNT_GPU_BACKEND})
endif()
foreach(backend IN LISTS keccak_backends)
    add_test(NAME ${backend}_keccak_oracle COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/gpu/keccak_oracle.py"
        --binary $<TARGET_FILE:${backend}_keccak_probe>
        --report "${CMAKE_CURRENT_BINARY_DIR}/${backend}-keccak-oracle.json")
    set_tests_properties(${backend}_keccak_oracle PROPERTIES TIMEOUT 120 LABELS "cpu;keccak;oracle")
    if(NOT backend STREQUAL "portable")
        set_tests_properties(${backend}_keccak_oracle PROPERTIES LABELS "${backend};hardware;keccak;oracle" RESOURCE_LOCK gpu_device)
    endif()
endforeach()
