add_executable(hash160_search_test tests/unit/hash160_search.cpp)
target_link_libraries(hash160_search_test PRIVATE keyhunt_core)
keyhunt_configure_target(hash160_search_test)
add_test(NAME hash160_search_contract COMMAND hash160_search_test)
set_tests_properties(hash160_search_contract PROPERTIES TIMEOUT 30 LABELS "cpu;core;hash160")

add_executable(portable_hash160_probe tests/gpu/hash160_probe.cpp)
target_include_directories(portable_hash160_probe PRIVATE kernels)
keyhunt_configure_target(portable_hash160_probe)
set(hash160_backends portable)
if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_hash160_probe tests/gpu/hash160_probe.hip)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_hash160_probe PRIVATE keyhunt_gpu_options)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_hash160_probe PRIVATE kernels src/backend/gpu)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_hash160_probe PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF LINKER_LANGUAGE CXX)
    list(APPEND hash160_backends ${KEYHUNT_GPU_BACKEND})
endif()
foreach(backend IN LISTS hash160_backends)
    add_test(NAME ${backend}_hash160_oracle COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/gpu/hash160_oracle.py"
        --binary $<TARGET_FILE:${backend}_hash160_probe>
        --report "${CMAKE_CURRENT_BINARY_DIR}/${backend}-hash160-oracle.json")
    set_tests_properties(${backend}_hash160_oracle PROPERTIES TIMEOUT 120 LABELS "cpu;hash160;oracle")
    if(NOT backend STREQUAL "portable")
        set_tests_properties(${backend}_hash160_oracle PROPERTIES LABELS "${backend};hardware;hash160;oracle" RESOURCE_LOCK gpu_device)
    endif()
endforeach()
