add_executable(minikey_search_test tests/unit/minikey_search.cpp)
target_link_libraries(minikey_search_test PRIVATE keyhunt_core)
keyhunt_configure_target(minikey_search_test)
add_test(NAME minikey_search_contract COMMAND minikey_search_test)
set_tests_properties(minikey_search_contract PROPERTIES TIMEOUT 60 LABELS "cpu;core;minikeys")

add_executable(portable_minikey_probe tests/gpu/minikey_probe.cpp)
target_include_directories(portable_minikey_probe PRIVATE kernels)
keyhunt_configure_target(portable_minikey_probe)
set(minikey_backends portable)
if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_minikey_probe tests/gpu/minikey_probe.hip)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_minikey_probe PRIVATE keyhunt_gpu_options)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_minikey_probe PRIVATE kernels src/backend/gpu)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_minikey_probe PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF LINKER_LANGUAGE CXX)
    list(APPEND minikey_backends ${KEYHUNT_GPU_BACKEND})
endif()
foreach(backend IN LISTS minikey_backends)
    add_test(NAME ${backend}_minikey_oracle COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/gpu/minikey_oracle.py"
        --binary $<TARGET_FILE:${backend}_minikey_probe>
        --report "${CMAKE_CURRENT_BINARY_DIR}/${backend}-minikey-oracle.json")
    set_tests_properties(${backend}_minikey_oracle PROPERTIES TIMEOUT 120 LABELS "cpu;minikey;oracle")
    if(NOT backend STREQUAL "portable")
        set_tests_properties(${backend}_minikey_oracle PROPERTIES LABELS "${backend};hardware;minikey;oracle" RESOURCE_LOCK gpu_device)
    endif()
endforeach()
