add_executable(minikey_search_test tests/unit/minikey_search.cpp)
target_link_libraries(minikey_search_test PRIVATE keyhunt_core)
keyhunt_configure_target(minikey_search_test)
add_test(NAME minikey_search_contract COMMAND minikey_search_test)
set_tests_properties(minikey_search_contract PROPERTIES TIMEOUT 60 LABELS "cpu;core;minikeys")

add_executable(portable_minikey_probe tests/gpu/minikey_probe.cpp)
target_include_directories(portable_minikey_probe PRIVATE kernels)
keyhunt_configure_target(portable_minikey_probe)
set(minikey_backends portable)
if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_minikey_probe tests/gpu/minikey_probe.hip)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_minikey_probe PRIVATE keyhunt_gpu_options)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_minikey_probe PRIVATE kernels src/backend/gpu)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_minikey_probe PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF LINKER_LANGUAGE CXX)
    list(APPEND minikey_backends ${KEYHUNT_GPU_BACKEND})
endif()
foreach(backend IN LISTS minikey_backends)
    add_test(NAME ${backend}_minikey_oracle COMMAND "${Python3_EXECUTABLE}"
        "${CMAKE_CURRENT_SOURCE_DIR}/tests/gpu/minikey_oracle.py"
        --binary $<TARGET_FILE:${backend}_minikey_probe>
        --report "${CMAKE_CURRENT_BINARY_DIR}/${backend}-minikey-oracle.json")
    set_tests_properties(${backend}_minikey_oracle PROPERTIES TIMEOUT 120 LABELS "cpu;minikey;oracle")
    if(NOT backend STREQUAL "portable")
        set_tests_properties(${backend}_minikey_oracle PROPERTIES LABELS "${backend};hardware;minikey;oracle" RESOURCE_LOCK gpu_device)
    endif()
endforeach()

if(KEYHUNT_ENABLE_GPU)
    add_executable(${KEYHUNT_GPU_BACKEND}_minikeys_executor_test tests/gpu/minikeys_executor.cpp)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_minikeys_executor_test PRIVATE keyhunt_gpu_options keyhunt_backend)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_minikeys_executor_test PROPERTIES LINKER_LANGUAGE CXX)
    add_executable(${KEYHUNT_GPU_BACKEND}_minikeys_failure_test tests/gpu/minikeys_failures.hip src/backend/gpu/minikeys.cpp)
    target_link_libraries(${KEYHUNT_GPU_BACKEND}_minikeys_failure_test PRIVATE keyhunt_gpu_options keyhunt_core)
    target_include_directories(${KEYHUNT_GPU_BACKEND}_minikeys_failure_test PRIVATE kernels kernels/search src/backend/gpu)
    target_compile_definitions(${KEYHUNT_GPU_BACKEND}_minikeys_failure_test PRIVATE KEYHUNT_TEST_GPU_FAILURES=1)
    set_target_properties(${KEYHUNT_GPU_BACKEND}_minikeys_failure_test PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF LINKER_LANGUAGE CXX)
    add_test(NAME ${KEYHUNT_GPU_BACKEND}_minikeys_executor COMMAND ${KEYHUNT_GPU_BACKEND}_minikeys_executor_test)
    add_test(NAME ${KEYHUNT_GPU_BACKEND}_minikeys_failures COMMAND ${KEYHUNT_GPU_BACKEND}_minikeys_failure_test)
    set_tests_properties(${KEYHUNT_GPU_BACKEND}_minikeys_executor ${KEYHUNT_GPU_BACKEND}_minikeys_failures
        PROPERTIES TIMEOUT 180 LABELS "${KEYHUNT_GPU_BACKEND};hardware;minikeys" RESOURCE_LOCK gpu_device)
endif()

set(minikeys_cli_args)
if(KEYHUNT_ENABLE_GPU)
    list(APPEND minikeys_cli_args --hardware --backend ${KEYHUNT_GPU_BACKEND})
endif()
add_test(NAME minikeys_cli COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/integration/minikeys_cli.py"
    --binary $<TARGET_FILE:keyhunt> --oracle $<TARGET_FILE:secp256k1_oracle>
    --report "${CMAKE_CURRENT_BINARY_DIR}/minikeys-cli-results.json" ${minikeys_cli_args})
set_tests_properties(minikeys_cli PROPERTIES TIMEOUT 600 LABELS "cpu;minikeys")
if(KEYHUNT_ENABLE_GPU)
    set_tests_properties(minikeys_cli PROPERTIES LABELS "${KEYHUNT_GPU_BACKEND};hardware;minikeys;oracle" RESOURCE_LOCK gpu_device)
endif()
